### ISSUE TITLE
About the experiments of ProFill in the paper

### ISSUE THREAD

**Issue by xianrui-luo** [yzhouas/TransFill-Reference-Inpainting#2]
Hi, in your paper, for the comparisons of ProFill you mentioned "We used the official pre-trained model from the authors. When testing, we fed in the target with the homography-warped source image." I wonder if you retrained the model with the modified inputs? It is a single image inpainting model and the pretrained model is for a single input. And I notice that ProFill has not released their pretrained model. I wonder how you get the model. Thank you.

**Comment by yzhouas** [comment]
Thanks for your interest in the paper. (1) we asked the authors of ProFill for the code and the pretrained model. If the model is not available, ProFill can be replaced with any new models like CoModGAN or LaMa etc. (2) We did finetune the ProFill model on RealEstate10K dataset to make it more fair, but the input will be in the same mode of the original paper. The CA inside ProFill will consider the global information to use, so it won't be highly influenced by the input type. When testing on ProFill, we concatenate the target and transformed source along the x dimension as the inputs. (Notice that it won't increase the input channel number of ProFill, but only the spatial size).

**Comment by xianrui-luo** [comment]
Thank you for the response!
